### ISSUE TITLE
30 minutes hard coded

### ISSUE THREAD

**Issue by sanjmeh** [sounritesh/Mindshift-GH#4]
Why is this 30 minutes hard coded? What is it?

https://github.com/sounritesh/Mindshift-GH/blob/fa919751e56558b678a7b3662b55bcc976b1ab89/WH-Report/Modules/algorithms.py#L50

**Comment by sounritesh** [comment]
This is not really hard code. This is the way of defining default parameters in python for a function. So if we don't assign any value to --delta_t, default would be 30 minutes, else it would be --delta_t minutes
