### ISSUE TITLE
Commentary needed for each loop

### ISSUE THREAD

**Issue by sanjmeh** [sounritesh/Mindshift-GH#6]
for example this loop, there needs to be comments.
https://github.com/sounritesh/Mindshift-GH/blob/fa919751e56558b678a7b3662b55bcc976b1ab89/modules/algorithms.py#L171

**Comment by sounritesh** [comment]
The modules in the root of this repository are outside the scope of report generation, look for all files only inside WH-Report folder. The other files are for DBL work and are premature.
